# Project Euler - 2
# Question:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# I prefer to make it with a function. Because there'll be other fibonacci questions.

# I'll write those in my native language, Turkish. I hope it will be understandable. If not, please let me know and I'll translate it to English.
# I have those functions in my algorithm.py file, but I wanted to write it here as well, just because to make it easier to read.
def fibonacci_yazdir(adet):
    a = 0
    b = 1
    liste = []
    while a < adet:
        print(a) # I like to see the numbers as they are generated. It's not neccesary, but it's fun.
        a, b = b, a + b
        liste.append(a)
    return liste

total = 0 # Yes, it's english.
sayilar = fibonacci_yazdir(4000000)
for i in sayilar:
    if i % 2 == 0:
        total += i
print(total)
