# Project Euler - 12
# Question: 
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

n = 1 
toplam_bolen = 0 # Piggy bank for counting divisors

while toplam_bolen < 500:
    bolensayisi = 0 # Counter for divisors of the current triangle number
    triangle = n * (n + 1) // 2 # Calculate the nth triangle number
    sinir = int(triangle ** 0.5) # Calculate the square root of the triangle number to limit divisor checking
    for i in range (1, sinir):
        if triangle % i == 0:
            bolensayisi += 2 
        if i*i == triangle:
            bolensayisi -= 1 # If the triangle number is a perfect square, we counted the square root twice, so we subtract one
    toplam_bolen = bolensayisi # Update the total divisor count

    n += 1

print(bolensayisi)
print(n)
print(triangle) # I prefer to see every result in the end.
